version: '3'

services:

  etcd1:
    image: ${IMAGE}
    container_name: ${NAME_1}
    ports:
      - ${PORT1_0}:2379
      - ${PORT1_1}:2380
    restart: on-failure
    #environment:
    #  - ETCDCTL_API=3
    command: /usr/local/bin/etcd --data-dir=/etcd-data --name ${NAME_1} --initial-advertise-peer-urls http://${HOST}:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://${HOST}:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster ${CLUSTER} --initial-cluster-state ${CLUSTER_STATE} --initial-cluster-token ${TOKEN} --heartbeat-interval 250 --election-timeout 1250