scope: pg_cluster
#namespace: /service/
name: patroni1

restapi:
    listen: 10.46.1.195:8008
    connect_address: 10.46.1.195:8008

etcd:
    hosts: 10.46.1.192:2379,10.46.1.193:2379,10.46.1.194:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 10.46.1.195/32 md5
  - host replication replicator 10.46.1.196/32 md5
  - host replication replicator 10.46.1.197/32 md5
  - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 10.46.1.195:5432
  connect_address: 10.46.1.195:5432
  data_dir: /data/pg
  bin_dir: /usr/lib/postgresql/14/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: postgres

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
